### PR TITLE
feat: add 8 digit based floats to output of /balances

### PR DESCRIPTION
**Pull request by l3gacyb3ta**

### CODE REVIEW

**Comment by l3gacyb3ta** [comment]
oops some of the files changed aren't the right ones

**Comment by l3gacyb3ta** [comment]
Maybe I'll just close this and reopen

**Comment by quackduck** [comment]
Yeah and could you work on a fresh fork? It’ll make things way easier

**Comment by l3gacyb3ta** [comment]
y u p

**Comment by quackduck** [comment]
Thanks!

**Pull request closed without merging**
