### PR TITLE
fix: add color onto 'Gotta restart' messages

### PR DESCRIPTION
**Pull request by l3gacyb3ta**
Owo now it's pretty and yellow!

### CODE REVIEW

**Comment by quackduck** [comment]
Why not make it red since it’s a bad thing? We could even decide the color of the server returned message based on http statuses

**Comment by l3gacyb3ta** [comment]
Well red is an error, but that isnt an error

**Comment by quackduck** [comment]
Red just means bad in general, we could make it orange by using the gchalk library

**Comment by l3gacyb3ta** [comment]
Ooo that sounds great

**Comment by quackduck** [comment]
Okay, I messed some of the git history up, really really sorry. Do you remember what changes you made? If so, please do make a new PR with your changes!

Sorry 😬

**Comment by l3gacyb3ta** [comment]
ooooof

**Comment by l3gacyb3ta** [comment]
it's ok, I'll do the gchalk thing!

**Comment by l3gacyb3ta** [comment]
Checkout #6 !

**Pull request closed without merging**
